#!/usr/bin/env python

import sys
import os


import cbopensource.connectors.reversinglabsa1000.bridge as bridge
from cbopensource.connectors.reversinglabsa1000 import __version__

if __name__ == "__main__":
    name = "reversinglabsa1000"
    deamon = bridge.ReversingLabsA1000Connector(name,
                                           configfile="/etc/cb/integrations/reversinglabs-a1000/connector.conf",
                                           work_directory="/usr/share/cb/integrations/reversinglabs-a1000/db",
                                           logfile="/var/log/cb/integrations/reversinglabs-a1000/reversinglabs.log")

    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            deamon.start()
        elif 'stop' == sys.argv[1]:
            deamon.stop()
        elif 'restart' == sys.argv[1]:
            deamon.restart()
        elif 'version' == sys.argv[1]:
            print "%s - version %s" % (name, __version__)
        else:
            print "Unknown command: %s" % sys.argv[1]
    else:
        print "Usage: %s start|stop|restart|version"
        sys.exit(2)

    sys.exit(0)
